version: '3.4'
services:
  raceproxy:
    container_name: raceproxy
    build:
      context: ./packages/proxy/.
      dockerfile: Dockerfile
    ports:
      - '443:443'
      - '80:80'
      # - "443:8443"
    image: rp-proxy

  racer:
    container_name: racer
    build:
      context: ./packages/racer/.
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    image: rp-racer
