version: '3.4'
services:
  raceproxy:
    container_name: raceproxy
    build:
      context: ./packages/proxy/.
      dockerfile: Dockerfile
    ports:
      - ${RACEPROXY_PORT:-443}:${RACEPROXY_PORT:-443}
    image: rp-proxy

  racer:
    container_name: racer
    build:
      context: ./packages/racer/.
      dockerfile: Dockerfile
    ports:
      - ${RACER_PORT:-3000}:${RACER_PORT:-3000}
    image: rp-racer
    environment:
      - RACER_PORT=${RACER_PORT:-3000}
