version: '3.4'
services:
  raceproxy:
    container_name: raceproxy
    build:
      context: ./packages/proxy/.
      dockerfile: Dockerfile
    ports:
      - ${RACEPROXY_PORT:-443}:${RACEPROXY_PORT:-443}
    image: rp-proxy
    restart: always
  racer:
    container_name: racer
    build:
      context: ./packages/racer/.
      dockerfile: Dockerfile
    depends_on:
      - raceproxy
    ports:
      - ${RACER_PORT:-3000}:${RACER_PORT:-3000}
    image: rp-racer
    environment:
      - RACER_PORT=${RACER_PORT:-3000}
    restart: always
  racepoint:
    container_name: racepoint
    build:
      context: ./packages/race-cli/.
      dockerfile: Dockerfile
    depends_on:
      - raceproxy
      - racer
    environment:
      - RACER_SERVER=http://racer
      # - LOG_LEVEL=debug
    volumes:
      - './results:/rp/results'
