#!/usr/bin/env bash
set -euo pipefail

cd ./packages/race-cli
echo "Building Racepoint CLI Docker image..."
docker build -t wayfairossdev/racepoint-cli:${RELEASE_VERSION} -t wayfairossdev/racepoint-cli:latest .
echo "Pushing Racepoint CLI Docker image to Docker Hub..."
docker push --all-tags wayfairossdev/racepoint-cli

cd ../racer
echo "Building Racepoint racer Docker image..."
docker build -t wayfairossdev/racepoint-racer:${RELEASE_VERSION} -t wayfairossdev/racepoint-racer:latest .
echo "Pushing Racepoint racer Docker image to Docker Hub..."
docker push --all-tags wayfairossdev/racepoint-racer

cd ../proxy
echo "Building Racepoint proxy Docker image..."
docker build -t wayfairossdev/racepoint-proxy:${RELEASE_VERSION} -t wayfairossdev/racepoint-proxy:latest .
echo "Pushing Racepoint proxy Docker image to Docker Hub..."
docker push --all-tags wayfairossdev/racepoint-proxy