name: Check Version Bump

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  check-version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Check for main version bump
        id: check-main
        uses: EndBug/version-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          diff-search: true
          file-name: ./package.json
