name: Check Version Bump

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  check-version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Check for version bump
        uses: del-systems/check-if-version-bumped@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        file-name: ./package.json
