# This pipeline needs to do these things:
# 1. Checkout package
# 2. Install NPM & dependencies
# 3. Check versions
# 4. Run tests
#

name: Checks

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout' # Download code from the repository
        uses: actions/checkout@v2 # Public action
        with:
          fetch-depth: 0 # Checkout all branches and tags

      - name: 'Use NodeJS 16' # Setup node using version 16
        uses: actions/setup-node@v2 # Public action
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install -g yarn-workspaces

      - name: Install modules
        run: yarn && yarn run build

      - name: Run tests # Run tests of all packages
        run: yarn workspaces run test

  # checkVersion:
  #   name: Check package version
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     # Use this GitHub Action
  #     - name: Check package version
  #       uses: technote-space/package-version-check-action@v1
  #       with:
  #         BRANCH_PREFIX: release/
