name: Publish

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths-ignore:
      - '**.md'
jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node
        uses: actions/setup-node@v3.3.0
        with:
          node-version: '16'

      - name: Checkout files
        uses: actions/checkout@v4

      - name: Install modules
        run: yarn && yarn run build

      - name: Extract package version
        id: extract-version
        uses: Saionaro/extract-package-version@v1.1.1

      - name: Release Latest
        id: release-version
        if: steps.extract-version.outcome == 'success'
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: 'v${{ steps.extract-version.outputs.version }}'
          prerelease: false

      - name: Login to Docker Hub
        id: docker-login
        if: steps.release-version.outcome == 'success'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy Images
        if: steps.docker-login.outcome == 'success'
        run: bash ./.github/actions/deploy_images
        env:
          RELEASE_VERSION: ${{ steps.extract-version.outputs.version }}
