name: Publish

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node
        uses: actions/setup-node@v3.1.0
        with:
          node-version: '16'

      - name: Checkout files
        uses: actions/checkout@v3

      - name: Install modules
        run: yarn && yarn run build

      - name: Check for version bump
        id: check-main
        uses: EndBug/version-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          diff-search: true

      - name: Check for racer version bump
        id: check-racer
        uses: EndBug/version-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          diff-search: true
          file-name: ./packages/racer/package.json

      - name: Check for proxy version bump
        id: check-proxy
        uses: EndBug/version-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          diff-search: true
          file-name: ./packages/proxy/package.json

      - name: Check for CLI version bump
        id: check-cli
        uses: EndBug/version-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          diff-search: true
          file-name: ./packages/race-cli/package.json

      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6

      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: 'v${{ steps.extract_version.outputs.version }}'
          prerelease: false
