name: Publish

on:
  pull_request:
    types: [closed]
    branches:
      - development
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true # Condition
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout' # Download code from the repository
        uses: actions/checkout@v2 # Public action
        with:
          fetch-depth: 0 # Checkout all branches and tags

      - name: 'Use NodeJS 16' # Setup node using version 16
        uses: actions/setup-node@v2 # Public action
        with:
          node-version: '16'
