name: Publish

on:
  pull_request:
    # types: [closed]
    types: [opened, synchronize]
    # branches:
    #   - development-test
    #   # - main

jobs:
  publish:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node
        uses: actions/setup-node@v3.1.0
        with:
          node-version: '16'

      - name: Checkout files
        uses: actions/checkout@v3

      - name: Install modules
        run: yarn && yarn run build

      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          # automatic_release_tag: 'latest'
          # prerelease: true
          # title: "Development Build"
          files: |
            LICENSE.txt
            *.jar
        # with:
        #   path: custom_path_to_repo
        #   isUseGithubRunNumber: false
        #   offset: 77

      # - name: 'Version and publish'
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     git config user.name "${{ github.actor }}"
      #     git config user.email "${{ github.actor }}@users.noreply.github.com"

      #     git log -1
      #     git fetch --tags
      #     git tag

      #     echo "============ JASON here 1 ======="
      #     yarn lerna changed

      #     echo "============ JASON here 2 ======="
      #     yarn lerna publish --force-publish from-git --yes
