name: Publish

on:
  pull_request:
    # types: [closed]
    types: [opened, synchronize]
    # branches:
    #   - development-test
    #   # - main

jobs:
  publish:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          # ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Install dependencies
        run: npm install lerna

      # - name: Install modules
      #   run: yarn && yarn build

      - name: 'Use NodeJS 16'
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: 'Version and publish'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout ${{ github.ref }}

          npx lerna version --conventional-commits --conventional-graduate --yes --force-git-tag
          npx lerna publish from-git --yes
