name: Run Javascript Tests

on: ['push', 'pull_request']

jobs:
  run-javascript-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node
        uses: actions/setup-node@v3.1.0
        with:
          node-version: '16'

      - name: Checkout files
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install -g yarn-workspaces

      - name: Install modules
        run: yarn && yarn run build

      - name: Lint
        run: yarn lint

      - name: Run tests
        run: yarn workspaces run test

  check-version-bump:
    runs-on: ubuntu-latest
    # branches:
    #   - main
    # paths-ignore:
    #   - '**.md'
    steps:
      - name: Check for version bump
        uses: del-systems/check-if-version-bumped@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
