name: Run Javascript Tests
on: [push]
jobs:
  run-javascript-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3.1.0
        with:
          node-version: '16'
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install -g yarn-workspaces
      - name: Install modules
        run: yarn && yarn run build
      - name: Run tests
        run: yarn workspaces run test
